# $schema:https://json.schemastore.org/github-action.json
name: "Create index pages for a melange package repo"
description: "Create index pages for a melange package repo"

inputs:
  repo-dir:
    description: "Path to the melange package repo"
    required: true

runs:
  using: "composite"

  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@ae62891fec2bb8e7d6c99fc78c9fec3a63790f8d # v10.0.0
      with:
        version-file: "${{ github.action_path }}/.tool-versions"
        ignore-empty-workdir: "true"
        cache-dependency-glob: |
          ${{ github.action_path }}/**/*.py.lock

    - name: Generate index pages
      shell: bash
      env:
        REPO_DIR: ${{ inputs.repo-dir }}
      run: |
        set -euo pipefail

        uv run --locked --script "${GITHUB_ACTION_PATH}/generate-index-pages.py" "${REPO_DIR}"

